
import React from 'react';

interface ResultViewProps {
  resultSrc: string;
}

const ResultView: React.FC<ResultViewProps> = ({ resultSrc }) => {
  // Helper to determine correct src format
  const getSrc = (src: string) => {
    if (src.startsWith('http') || src.startsWith('blob:') || src.startsWith('data:')) {
        return src;
    }
    return `data:image/png;base64,${src}`;
  };

  return (
    <div className="w-full h-full relative group">
      <img 
        src={getSrc(resultSrc)} 
        alt="Generated Result" 
        className="w-full h-full object-contain bg-[#050505]"
      />
      
      {/* Subtle watermark/badge */}
      <div className="absolute bottom-3 right-3 px-2 py-1 bg-black/60 backdrop-blur-md rounded text-[10px] font-medium text-[#CCFF00]/80 border border-[#CCFF00]/20 pointer-events-none">
        Generated by INK
      </div>
    </div>
  );
};

export default ResultView;
